server:
  port: 8083

spring:
  application:
    name: user-service

  datasource:
    url: jdbc:postgresql://localhost:5432/Decision_DB
    username: postgres
    password: 54321
    driver-class-name: org.postgresql.Driver

  jpa:
    hibernate:
      ddl-auto: validate
    show-sql: true
    properties:
      hibernate.format_sql: true

  cloud:
    consul:
      host: localhost
      port: 8500
      discovery:
        service-name: user-service
        register: true
        prefer-ip-address: true
        health-check-path: /actuator/health
        health-check-interval: 10s

management:
  endpoints:
    web:
      exposure:
        include: health

logging:
  level:
    org.springframework.web: INFO
    org.hibernate.SQL: DEBUG

jwt:
  secret: ${JWT_SECRET:9a7261536444743777217a25432a462d4a614e645267556b5870327335763879}
  expiration: 28800000

app:
  security:
    cors:
      allowed-origins:
        - http://localhost:5500