server:
  port: 8081

spring:
  application:
    name: decision-service


  datasource:
    url: jdbc:postgresql://${DB_HOST:localhost}:${DB_PORT:5432}/${DB_NAME:Decision_IS}
    username: ${DB_USERNAME:postgres}
    password: ${DB_PASSWORD:54321}
    driver-class-name: org.postgresql.Driver

  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate.format_sql: true
      hibernate:
        query:
          plan_cache_max_size: 2048
        type:
          preferred_uuid_jdbc_type: CHAR

  cloud:
    consul:
      host: ${CONSUL_HOST:localhost}
      port: ${CONSUL_PORT:8500}
      discovery:
        service-name: decision-service
        register: true
        prefer-ip-address: true
        health-check-path: /actuator/health
        health-check-interval: 10s
        instance-id: ${spring.application.name}:${server.port}:${random.value}

management:
  endpoints:
    web:
      exposure:
        include: health

logging:
  level:
    org.springframework.web: INFO
    org.hibernate.SQL: DEBUG

app:
  security:
    cors:
      allowed-origins: ${FRONTEND_URL:http://localhost:5500,http://127.0.0.1:5500}

jwt:
  secret: ${JWT_SECRET:YTIzNDU2Nzg5MGFiY2RlZmdoaWprbG1ub3BxcnN0dXZ3eHl6TUI0NTY3ODkwYmNkZWZnaGlqa2xtbm9wY3JzdHV2dw==}
  expiration: 28800000

